# Generated by Django 5.2 on 2025-04-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_newslettersubscriber_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={},
        ),
    ]
