# Generated by Django 5.2 on 2025-04-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='instructor',
            field=models.CharField(default='To be announced', max_length=100),
        ),
        migrations.AddField(
            model_name='posts',
            name='nextSession',
            field=models.DateField(default='2023-10-01'),
        ),
        migrations.AddField(
            model_name='posts',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='posts',
            name='students',
            field=models.IntegerField(default=0),
        ),
    ]
